//
//  aqiProtocols.swift
//  aqiStoryBoard
//
//  Created armyxx on 9/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol aqiWireframeProtocol: class {

}
//MARK: Presenter -
protocol aqiPresenterProtocol: class {

}

//MARK: Interactor -
protocol aqiInteractorProtocol: class {

  var presenter: aqiPresenterProtocol?  { get set }
}

//MARK: View -
protocol aqiViewProtocol: class {

  var presenter: aqiPresenterProtocol?  { get set }
}
