//
//  aqiRouter.swift
//  aqiStoryBoard
//
//  Created armyxx on 9/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class aqiRouter: aqiWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = aqiViewController(nibName: nil, bundle: nil)
        let interactor = aqiInteractor()
        let router = aqiRouter()
        let presenter = aqiPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
