//
//  aqiViewController.swift
//  aqiStoryBoard
//
//  Created armyxx on 9/11/2564 BE.
//  Copyright © 2564 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class aqiViewController: UIViewController, aqiViewProtocol {

    var presenter: aqiPresenterProtocol?

    override func viewDidLoad() {
        super.viewDidLoad()
    }

}
